### ISSUE TITLE
store Q decomposition to get exp(Q*t) repeatedly?

### ISSUE THREAD

**Issue by cecileane** [jangevaare/PhyloModels.jl#1]
Hi Justin, thanks for these tools! We would like to use your types and functions to add analysis methods for discrete traits in [PhyloNetworks](https://github.com/crsl4/PhyloNetworks.jl). In your implementation of general rate matrices, when there is no analytical formulation of the transition probabilities, your `P` function performs a matrix exponential each time it's called:

```julia
function P(gtr::GTR, t::Float64)
  if t < 0.
    error("Time must be positive")
  end
  return expm(Q(gtr)*t)
end
```

The Q matrix has the same eigenvalues/vectors for all branches and for all tree topologies. So did you think about storing the eigen-decomposition of Q in some way, to use it repeatedly on different branches and when the tree topology changes, rather than re-calculating the decomposition each time for each branch? or did I miss something?

I'll tag @crsl4, @mkborregaard and @pbastide, who are interested in cross-compatibility between Julia packages for biology and evolution.

**Comment by mkborregaard** [comment]
Also tagging @Ward9250 :-)

**Comment by jangevaare** [comment]
Yes, that would be an easy to add and worthwhile addition I think! Perhaps as a first stab a function which accepted a vector of branch lengths, and returned a vector of P matrices (reusing the decomposition of Q) would work.

**Comment by cecileane** [comment]
If you plan to add to [PhyloTrees](https://github.com/jangevaare/PhyloTrees.jl) some kind of likelihood optimization with a search over trees, you might want to re-use the decomposition of Q across different tree topologies. In this case, an idea might be to add to your GTR type a field for the eigenvectors and another field for eigenvalues. The P function, when given a GTR type, could then use these 2 fields anytime: across different branch lengths of the same or different tree topologies. Just an idea.

**Comment by jangevaare** [comment]
Thanks @cecileane. I don't think that will end up in PhyloTrees.jl, which I will leave as very minimum utilities for working with phylogenetic trees, but MCMC functionality certainly is a goal of PhyloModels.jl

**Comment by jangevaare** [comment]
This is a pretty old issue, but I have added something for this for GTR models, where there can be computational savings by storing eigen decomposition of the Q matrix in commit 914acd5a836b1ff2eb4d1a848e731b07fa31d398. 

```"Generate an array of P matrices for a specified array of times"
function P(gtr::GTR, t::Array{Float64})
  if any(t .< 0.0)
    error("t must be positive")
  end
  eig_vals, eig_vecs = eig(Q(mod))
  return [expm(eig_vecs * (diagm(eig_vals)*i) * eig_vecs') for i in t]
end
```

I will no longer be developing PhyloModels.jl, I have instead been working on a new package for the BioJulia ecosystem - BioJulia/SubstitutionModels.jl for Julia 0.6+. This package uses StaticArrays for P and Q matrices, which is a good bit quicker for most models than this package. StaticArrays doesn't currently have a specialized matrix exponential function for 4x4 static matrices, so the default linalg expm is still used, meaning that P matrices for the GTR may not be any quicker.
